In [43]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
df= pd.read_csv('data/50_Startups.csv')

In [30]:
#Dividing dependent and independent variables.
x= df.drop('Profit', axis=1)
y= df['Profit']
x

    R&D Spend  Administration  Marketing Spend       State
0   165349.20       136897.80        471784.10    New York
1   162597.70       151377.59        443898.53  California
2   153441.51       101145.55        407934.54     Florida
3   144372.41       118671.85        383199.62    New York
4   142107.34        91391.77        366168.42     Florida
5   131876.90        99814.71        362861.36    New York
6   134615.46       147198.87        127716.82  California
7   130298.13       145530.06        323876.68     Florida
8   120542.52       148718.95        311613.29    New York
9   123334.88       108679.17        304981.62  California
10  101913.08       110594.11        229160.95     Florida
11  100671.96        91790.61        249744.55  California
12   93863.75       127320.38        249839.44     Florida
13   91992.39       135495.07        252664.93  California
14  119943.24       156547.42        256512.92     Florida
15  114523.61       122616.84        261776.23    New York
16   78013.11       121597.55        264346.06  California
17   94657.16       145077.58        282574.31    New York
18   91749.16       114175.79        294919.57     Florida
19   86419.70       153514.11             0.00    New York
20   76253.86       113867.30        298664.47  California
21   78389.47       153773.43        299737.29    New York
22   73994.56       122782.75        303319.26     Florida
23   67532.53       105751.03        304768.73     Florida
24   77044.01        99281.34        140574.81    New York
25   64664.71       139553.16        137962.62  California
26   75328.87       144135.98        134050.07     Florida
27   72107.60       127864.55        353183.81    New York
28   66051.52       182645.56        118148.20     Florida
29   65605.48       153032.06        107138.38    New York
30   61994.48       115641.28         91131.24     Florida
31   61136.38       152701.92         88218.23    New York
32   63408.86       129219.61         46085.25  California
33   55493.95       103057.49        214634.81     Florida
34   46426.07       157693.92        210797.67  California
35   46014.02        85047.44        205517.64    New York
36   28663.76       127056.21        201126.82     Florida
37   44069.95        51283.14        197029.42  California
38   20229.59        65947.93        185265.10    New York
39   38558.51        82982.09        174999.30  California
40   28754.33       118546.05        172795.67  California
41   27892.92        84710.77        164470.71     Florida
42   23640.93        96189.63        148001.11  California
43   15505.73       127382.30         35534.17    New York
44   22177.74       154806.14         28334.72  California
45    1000.23       124153.04          1903.93    New York
46    1315.46       115816.21        297114.46     Florida
47       0.00       135426.92             0.00  California
48     542.05        51743.15             0.00    New York
49       0.00       116983.80         45173.06  California

In [31]:
dummies= pd.get_dummies(x.State)
dummies

    California  Florida  New York
0            0        0         1
1            1        0         0
2            0        1         0
3            0        0         1
4            0        1         0
5            0        0         1
6            1        0         0
7            0        1         0
8            0        0         1
9            1        0         0
10           0        1         0
11           1        0         0
12           0        1         0
13           1        0         0
14           0        1         0
15           0        0         1
16           1        0         0
17           0        0         1
18           0        1         0
19           0        0         1
20           1        0         0
21           0        0         1
22           0        1         0
23           0        1         0
24           0        0         1
25           1        0         0
26           0        1         0
27           0        0         1
28           0        1         0
29           0        0         1
30           0        1         0
31           0        0         1
32           1        0         0
33           0        1         0
34           1        0         0
35           0        0         1
36           0        1         0
37           1        0         0
38           0        0         1
39           1        0         0
40           1        0         0
41           0        1         0
42           1        0         0
43           0        0         1
44           1        0         0
45           0        0         1
46           0        1         0
47           1        0         0
48           0        0         1
49           1        0         0

In [32]:
merged= pd.concat([x, dummies], axis= 'columns')
merged.drop(['State','California'], axis='columns', inplace=True)
merged

    R&D Spend  Administration  Marketing Spend  Florida  New York
0   165349.20       136897.80        471784.10        0         1
1   162597.70       151377.59        443898.53        0         0
2   153441.51       101145.55        407934.54        1         0
3   144372.41       118671.85        383199.62        0         1
4   142107.34        91391.77        366168.42        1         0
5   131876.90        99814.71        362861.36        0         1
6   134615.46       147198.87        127716.82        0         0
7   130298.13       145530.06        323876.68        1         0
8   120542.52       148718.95        311613.29        0         1
9   123334.88       108679.17        304981.62        0         0
10  101913.08       110594.11        229160.95        1         0
11  100671.96        91790.61        249744.55        0         0
12   93863.75       127320.38        249839.44        1         0
13   91992.39       135495.07        252664.93        0         0
14  119943.24       156547.42        256512.92        1         0
15  114523.61       122616.84        261776.23        0         1
16   78013.11       121597.55        264346.06        0         0
17   94657.16       145077.58        282574.31        0         1
18   91749.16       114175.79        294919.57        1         0
19   86419.70       153514.11             0.00        0         1
20   76253.86       113867.30        298664.47        0         0
21   78389.47       153773.43        299737.29        0         1
22   73994.56       122782.75        303319.26        1         0
23   67532.53       105751.03        304768.73        1         0
24   77044.01        99281.34        140574.81        0         1
25   64664.71       139553.16        137962.62        0         0
26   75328.87       144135.98        134050.07        1         0
27   72107.60       127864.55        353183.81        0         1
28   66051.52       182645.56        118148.20        1         0
29   65605.48       153032.06        107138.38        0         1
30   61994.48       115641.28         91131.24        1         0
31   61136.38       152701.92         88218.23        0         1
32   63408.86       129219.61         46085.25        0         0
33   55493.95       103057.49        214634.81        1         0
34   46426.07       157693.92        210797.67        0         0
35   46014.02        85047.44        205517.64        0         1
36   28663.76       127056.21        201126.82        1         0
37   44069.95        51283.14        197029.42        0         0
38   20229.59        65947.93        185265.10        0         1
39   38558.51        82982.09        174999.30        0         0
40   28754.33       118546.05        172795.67        0         0
41   27892.92        84710.77        164470.71        1         0
42   23640.93        96189.63        148001.11        0         0
43   15505.73       127382.30         35534.17        0         1
44   22177.74       154806.14         28334.72        0         0
45    1000.23       124153.04          1903.93        0         1
46    1315.46       115816.21        297114.46        1         0
47       0.00       135426.92             0.00        0         0
48     542.05        51743.15             0.00        0         1
49       0.00       116983.80         45173.06        0         0

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test= train_test_split(merged,y, test_size=0.2, random_state=0)

In [39]:
from sklearn.linear_model import LinearRegression
clf= LinearRegression()
clf.fit(x_train,y_train);

In [40]:
#Predicting the results
y_preds= clf.predict(x_test)
y_preds

array([103015.20159796, 132582.27760816, 132447.73845174,  71976.09851258,
       178537.48221055, 116161.24230165,  67851.69209676,  98791.73374687,
       113969.43533012, 167921.0656955 ])

In [48]:
#Backward elimination
import statsmodels.api as sm
merged=np.append(arr=np.ones((50,1)).astype(int), values= merged , axis=1)

In [51]:
x_opt=merged[:,[0,1,2,3,4,5]]
regressor_OLS=sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Tue, 06 Jul 2021   Prob (F-statistic):           8.49e-29
Time:                        16:48:51   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.505e+04   3323.935      7.537      0.000    1.84e+04    3.17e+04
x1          2.505e+04   3323.935      7.537      0.000    1.84e+04    3.17e+04
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
x5           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     8.18e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.79e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [52]:
x_opt=merged[:,[0,1,2,3,4]]
regressor_OLS=sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Tue, 06 Jul 2021   Prob (F-statistic):           4.53e-30
Time:                        16:53:36   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.506e+04   3286.176      7.626      0.000    1.84e+04    3.17e+04
x1          2.506e+04   3286.176      7.626      0.000    1.84e+04    3.17e+04
x2             0.8057      0.045     17.846      0.000       0.715       0.897
x3            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x4             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.89e+18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.09e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [53]:
x_opt=merged[:,[0,1,2,4]]
regressor_OLS=sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Tue, 06 Jul 2021   Prob (F-statistic):           2.16e-31
Time:                        16:55:04   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.349e+04   1344.966     17.464      0.000    2.08e+04    2.62e+04
x1          2.349e+04   1344.966     17.464      0.000    2.08e+04    2.62e+04
x2             0.7966      0.041     19.266      0.000       0.713       0.880
x3             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     8.66e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.38e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [54]:
x_opt=merged[:,[0,1,2]]
regressor_OLS=sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Tue, 06 Jul 2021   Prob (F-statistic):           3.50e-32
Time:                        16:56:21   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.452e+04   1268.948     19.320      0.000     2.2e+04    2.71e+04
x1          2.452e+04   1268.948     19.320      0.000     2.2e+04    2.71e+04
x2             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.06e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""